apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-portal-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            backend:
              serviceName: portal-backend-svc
              servicePort: 80